### ISSUE TITLE
function covsel.filter is sensitive to certain characters

### ISSUE THREAD

**Issue by ptitle** [N-SDM/covsel#1]
Just a warning that if any predictor names contain `-` or `/` (maybe others), the function covsel.filter or covsel.filteralgo will crash, because at some point the predictor names get modified. 

```
library(covsel)
covdata<-data_covsel$env_vars

# add in some dashes
colnames(covdata) <- gsub('_', '-', colnames(covdata))

covdata_filter<-covsel.filteralgo(covdata, pa=data_covsel$pa)
Error in `[.data.frame`(covdata, , sanctuaire) :
  undefined columns selected
```

**Comment by N-SDM** [comment]
Hello @ptitle ,
Thank you for reporting! I just fixed covsel.filteralgo.R. The updated version should work properly devtools::install_github("N-SDM/covsel"). If not feel free to report again.
Best,
Antoine
